# https://docs.docker.com/compose/rails/

version: '3'

services:

  db:
    image: postgres:13.1
    restart: always
    env_file:
      - ~/.env/auja-rails/db.env
    ports:
      - "127.1.10.2:5432:5432" # pg-rails-erp.auja.test
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./tmp/latest.dump:/tmp/latest.dump

  rails_dev:
    build:
      context: .
      args:
        - RAILS_ENV=development
    command: tmuxinator start dev
    volumes:
      - .:/app
    ports:
      - "127.1.10.1:3000:3000" # rails-erp.auja.test
    env_file:
      - ~/.env/auja-rails/db.env
#    environment:
#      PAGER: "less -RS"
#      LC_ALL: "en_US.utf8" # for psql
    depends_on:
      - db

volumes:
  db-data:
