# https://docs.docker.com/compose/rails/

version: '3'

services:

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "127.1.10.1:3000:3000" # rails-erp.auja.test
    env_file:
      - ~/.env/auja-rails/db.env
    depends_on:
      - db

  db:
    image: postgres:13.1
    restart: always
    env_file:
      - ~/.env/auja-rails/db.env
    ports:
      - "127.1.10.2:5432:5432" # pg-rails-erp.auja.test
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./tmp/latest.dump:/tmp/latest.dump


volumes:
  db-data:
