#!/bin/bash

# Pre launch stuff
#mkdir -p /tmp/export # ensures root does not create this dir

set -x

# Optionally override and run custom commands
exec docker-compose run --rm --service-ports rails_dev "$@"
