# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: auja_erp_development

test:
  <<: *default
  database: auja_erp_test
